# Generated by Django 4.2 on 2023-04-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='housename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
